import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import {build} from 'esbuild';
import {Window} from 'happy-dom';
const root=fileURLToPath(new URL('../',import.meta.url));
const html=(await readFile(root+'index.html','utf8')).replace(/<script\b[^>]*>[\s\S]*?<\/script>/g,'').replace(/<link\b[^>]*>/g,'');
const bundle=await build({entryPoints:[root+'src/app.js'],bundle:true,write:false,format:'iife',plugins:[{name:'controlled-dom-environment',setup(build){build.onResolve({filter:/\/world\.js$/},()=>({path:'world',namespace:'fixture'}));build.onResolve({filter:/\/student\.js$/},()=>({path:'student',namespace:'fixture'}));build.onResolve({filter:/\/sdk\.js$/},()=>({path:'sdk',namespace:'fixture'}));build.onLoad({filter:/.*/,namespace:'fixture'},args=>({contents:args.path==='sdk'?`export class XUniversityClient {constructor(){return window.__client;}}`:args.path==='student'?`export function createStudentPreview(){return {setProfile(){}};}`:`export function createWorld(options){window.__world={position:{...options.position},settings:options.settings,stop(){},setStudent(profile){this.profile=profile;},applySettings(settings){this.settings=settings;},resetCamera(){this.cameraReset=true;},getPosition(){return {...this.position};},reset(){this.position={x:0,z:16};options.onSpace('gate');},walkTo(id){this.lastTarget=id;options.onSpace(id);options.onArrive(id);},enterManually(id){options.onSpace(id);}};return window.__world;}` }));}}]});
const stopEvent={preventDefault(){}};
const waitFor=async predicate=>{for(let i=0;i<100;i++){if(predicate())return;await new Promise(r=>setTimeout(r,2));}throw Error('UI state did not settle');};
function backend(){let n=0;const projects=new Map();const get=id=>{const p=projects.get(id);if(!p)throw Error('not found');return p;};const snapshot=p=>structuredClone(p);return {projects,async createSession({goal}){const session_id='test-'+(++n);projects.set(session_id,{session:{goal},messages:[],roadmap:null,quest:{status:'created'}});return {session_id};},async getSession(id){return snapshot(get(id));},async getQuest(id){return snapshot(get(id).quest);},async advanceQuest(body){const p=get(body.session_id),q=p.quest;if(['created','clarifying'].includes(q.status)||q.status==='quest_ready'&&body.message){p.messages.push({agent:'scholar',role:'user',content:body.message},{agent:'scholar',role:'assistant',content:'请确认项目范围'});q.status='quest_ready';}else if(q.status==='quest_ready'){p.roadmap={title:'测试路线',stages:['gate','library','professor_office','lab'].map((space,i)=>({id:'s'+i,name:space,space,tasks:Array.from({length:i?3:1},(_,j)=>({id:`t${i}-${j}`,title:'测试任务',space,status:'pending'}))}))};q.status='library';}else if(q.status==='library'){q.status='professor';q.library_result={retrieval_version:3,query:p.session.goal,documents:[],notice:'受控演示资料',arxiv_status:'ok',arxiv_papers:[{title:'受控论文显示验收',authors:['Test Author'],year:'2026',url:'https://arxiv.org/abs/1234.5678',snippet:'受控摘要'}]};}else if(q.status==='professor')q.status='lab';else if(q.status==='lab'){q.status='project_ready';q.project={title:'测试行动卡',artifact_type:'project_plan'};q.lab_result={overview:'测试方案',steps:[]};}return {};},async streamProfessorChat({session_id,message}){const p=get(session_id);p.messages.push({agent:'professor',role:'user',content:message},{agent:'professor',role:'assistant',content:'已收到，继续讨论'});p.quest.professor_result={answer:'已收到，继续讨论',references:[]};return {text:'已收到，继续讨论'};},async updateProgress(id,taskId,status){for(const s of get(id).roadmap.stages)for(const t of s.tasks)if(t.id===taskId)t.status=status;},async deleteSession(id){projects.delete(id);return {ok:true};}};}
test('whole app DOM flow: onboarding, projects, conversation, route, library, professor, card, all tasks, settings, cancel/delete, reload',async t=>{
 const window=new Window(),document=window.document;t.after(()=>window.happyDOM.close());document.write(html);window.__client=backend();window.fetch=async()=>new Response(JSON.stringify({mock_mode:true}),{status:200});window.URL.createObjectURL=()=> 'blob:test';window.URL.revokeObjectURL=()=>{};window.HTMLAnchorElement.prototype.click=function(){window.__download=this.download;};window.eval(bundle.outputFiles[0].text);
 const $=s=>document.querySelector(s),type=(id,value)=>{$(id).value=value;$(id).dispatchEvent(new window.Event('input'));};await waitFor(()=>!$('#submit-goal').disabled);
 assert.equal($('#student-panel').open,true);type('#nickname','验收同学');$('[value="female"]').checked=true;$('#student-form').onsubmit(stopEvent);assert.equal($('#projects-panel').open,true);
 type('#project-name','验收项目 A');$('#new-project-form').onsubmit(stopEvent);type('#goal','一个校园原型');await $('#goal-form').onsubmit(stopEvent);assert.equal($('#chat-form').hidden,false);type('#message','两周完成');await $('#chat-form').onsubmit(stopEvent);await $('#roadmap-button').onclick();
 $('#agent-panel').close();window.__world.enterManually('library');assert.equal($('#agent-panel').open,false,'manual exploration must not open a modal');$('[data-space="library"]').click();await waitFor(()=>window.__client.projects.get('test-1').quest.status==='professor'&&!$('#message').disabled);
 assert.match($('#knowledge').textContent,/受控论文显示验收/);assert.match($('#knowledge').textContent,/Test Author/);const queryDetails=$('#knowledge details[data-detail="library-query"]');queryDetails.open=true;window.__world.enterManually('library');assert.equal($('#knowledge details[data-detail="library-query"]').open,true);
 $('[data-space="office"]').click();await waitFor(()=>!!window.__client.projects.get('test-1').quest.professor_result&&!$('#message').disabled);type('#message','继续收敛问题');await $('#chat-form').onsubmit(stopEvent);await $('#space-action').onclick();await waitFor(()=>$('#panel-title').textContent.includes('X Lab'));await $('#space-action').onclick();assert.match($('#quest-title').textContent,/规划流程已完成/);$('#export-project').onclick();assert.equal(window.__download,'x-university-project-card.json');
 await $('#all-tasks-button').onclick();assert.equal(document.querySelectorAll('#all-tasks input').length,10);for(const id of [...document.querySelectorAll('#all-tasks input')].map(e=>e.dataset.taskId)){const input=$(`[data-task-id="${id}"]`);input.checked=true;await input.onchange();}assert.match($('#tasks-summary').textContent,/剩余 0 项/);assert.match($('#quest-title').textContent,/任务已全部勾选/);$('#tasks-panel .close').click();
 $('#settings').click();$('#quality').value='high';$('#quality').onchange();type('#camera-sensitivity','1.6');$('#reduce-motion').checked=true;$('#reduce-motion').onchange();assert.deepEqual(JSON.parse(JSON.stringify(window.__world.settings)),{quality:'high',sensitivity:1.6,reduceMotion:true});const before={...window.__world.position};$('#reset-camera').click();assert.deepEqual({...window.__world.position},before);assert.equal(window.__world.cameraReset,true);$('#reset-preferences').click();assert.equal(window.__world.settings.quality,'balanced');$('#settings-panel .close').click();
 $('#projects-button').click();type('#project-name','验收项目 B');$('#new-project-form').onsubmit(stopEvent);assert.equal($('#goal-form').hidden,false);assert.equal($('#chat-history').textContent,'');$('#agent-panel').close();$('#projects-button').click();
 const findCard=title=>[...document.querySelectorAll('.project-option')].find(card=>card.querySelector('h3').textContent===title);findCard('验收项目 A').querySelector('.danger').click();$('#cancel-delete-project').click();assert.ok(findCard('验收项目 A'));findCard('验收项目 A').querySelector('.danger').click();await $('#confirm-delete-project').onclick();assert.equal(findCard('验收项目 A'),undefined);assert.equal(window.__client.projects.size,0);
 while(document.querySelector('.project-option')){document.querySelector('.project-option .danger').click();await $('#confirm-delete-project').onclick();}assert.match($('#project-list').textContent,/还没有项目/);const saved=window.localStorage.getItem('xuni-campus-workspace-v2');assert.equal(JSON.parse(saved).projects.length,0);assert.equal(JSON.parse(saved).profile.nickname,'验收同学');
 const next=new Window();t.after(()=>next.happyDOM.close());next.document.write(html);next.localStorage.setItem('xuni-campus-workspace-v2',saved);next.__client=window.__client;next.fetch=window.fetch;next.eval(bundle.outputFiles[0].text);await waitFor(()=>!next.document.querySelector('#submit-goal').disabled);assert.match(next.document.querySelector('#project-list').textContent,/还没有项目/);assert.equal(next.document.querySelector('#student-button').textContent,'验收同学');await next.happyDOM.close();await window.happyDOM.close();
});
