import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {Window} from 'happy-dom';
import {createCampusShell} from '../src/shell.js';
const html=(await readFile(new URL('../index.html',import.meta.url),'utf8')).replace(/<script\b[^>]*>[\s\S]*?<\/script>/g,'').replace(/<link\b[^>]*>/g,'');
function setup(t){const window=new Window();t.after(()=>window.happyDOM.close());const document=window.document;document.write(html);const session={profile:{nickname:'小林'},state:{title:'项目 A',goal:'目标 A',quest:{status:'library'}},projects:[{title:'项目 A',quest:{status:'library'}}]};let view,night,target;const world={setView(v){view=v},setNight(n){night=n},stop(){}};const shell=createCampusShell({document,session,getWorld:()=>world,onNavigate:id=>target=id,onProjects(){},onStudent(){},onSettings(){},onAgent(){},onTasks(){},toast(){}});return {window,document,session,shell,get view(){return view},get night(){return night},get target(){return target},$:s=>document.querySelector(s)};}
test('view history goes backward and forward without teleporting; a new branch discards forward history',t=>{const f=setup(t);assert.equal(f.$('#dashboard').hidden,false);f.shell.setView('overview');f.shell.setView('first');f.$('#nav-back').click();assert.equal(f.view,'overview');f.$('#nav-back').click();assert.equal(f.shell.mode,'home');assert.equal(f.$('#nav-back').disabled,true);f.$('#nav-forward').click();assert.equal(f.view,'overview');f.shell.setView('third');assert.equal(f.$('#nav-forward').disabled,true);assert.equal(f.target,undefined);});
test('radial selection closes menu and navigates in third-person; project content updates without stale data',t=>{const f=setup(t);f.shell.setView('first');f.$('#radial-toggle').click();assert.equal(f.$('#radial-menu').hidden,false);f.$('#radial-items button:nth-child(4)').click();assert.equal(f.target,'lab');assert.equal(f.view,'third');assert.equal(f.$('#radial-menu').hidden,true);f.session.state={title:'项目 B',goal:'目标 B',quest:{status:'created'}};f.shell.render();assert.equal(f.$('#dashboard-project-title').textContent,'项目 B');assert.equal(f.$('#dashboard-goal').textContent,'目标 B');f.$('#night-toggle').click();assert.equal(f.night,true);});
test('building selection updates the room label and routes to the selected campus space',t=>{const f=setup(t);f.shell.setView('library');for(const [id,label] of [['office','研讨大厅'],['lab','实验大厅'],['gate','入口细节'],['library','阅读大厅']]){f.$('#building-study').value=id;f.$('#building-study').dispatchEvent(new f.window.Event('change'));assert.equal(f.$('[data-library-preset="inside"]').textContent,label);f.$('#library-enter').click();assert.equal(f.target,id);assert.equal(f.view,'third');}});
