import test from 'node:test';
import assert from 'node:assert/strict';
import {Window} from 'happy-dom';
import {readFile} from 'node:fs/promises';
import {ConnectedSession} from '../src/service.js';
import {taskProgress,projectStatus,renderTaskOverview} from '../src/tasks.js';
const html=(await readFile(new URL('../index.html',import.meta.url),'utf8')).replace(/<script\b[^>]*>[\s\S]*?<\/script>/g,'').replace(/<link\b[^>]*>/g,'');
const roadmap=()=>({stages:['gate','library','professor_office','lab'].map((space,i)=>({id:'s'+i,name:space,space,tasks:Array.from({length:i===0?1:3},(_,j)=>({id:`t${i}-${j}`,title:`${space} task ${j}`,deliverable:'检查此项产出',status:i===3?'done':'pending'}))}))});
function fixture(){const window=new Window(),document=window.document;document.write(html);let saved=roadmap();const writes=[],client={getSession:async()=>({session:{goal:'test'},roadmap:structuredClone(saved),messages:[]}),getQuest:async()=>({status:'project_ready'}),updateProgress:async(sid,id,status)=>{writes.push({sid,id,status});for(const stage of saved.stages)for(const task of stage.tasks)if(task.id===id)task.status=status;}};const storage={getItem:()=>null,setItem:()=>{}};let session;session=new ConnectedSession({storage,client,health:async()=>({}),onChange:()=>renderTaskOverview({document,session})});session.state.sessionId='test-project';session.state.quest.status='project_ready';session.state.roadmap=structuredClone(saved);renderTaskOverview({document,session});return {window,document,session,client,writes};}
test('all-space overview exposes the seven hidden tasks and their completion criteria',async()=>{const f=fixture(),inputs=[...f.document.querySelectorAll('#all-tasks input')];assert.equal(inputs.length,10);assert.equal(inputs.filter(i=>i.checked).length,3);assert.match(f.document.querySelector('#tasks-summary').textContent,/剩余 7 项/);assert.equal(f.document.querySelectorAll('.task-deliverable').length,10);assert.equal(projectStatus(f.session.state,''),'规划流程已完成');assert.match(f.document.querySelector('#tasks-explanation').textContent,/下载行动卡只保存计划/);await f.window.happyDOM.close();});
test('overview checkboxes save all tasks, survive sync, and undo returns remaining count',async()=>{const f=fixture();for(const task of taskProgress(f.session.state.roadmap).tasks.filter(t=>t.status!=='done')){const input=f.document.querySelector(`[data-task-id="${task.id}"]`);input.checked=true;await input.onchange();}await f.session.recover();assert.equal(f.writes.length,7);assert.ok(f.writes.every(w=>w.sid==='test-project'));assert.equal(taskProgress(f.session.state.roadmap).allDone,true);assert.match(projectStatus(f.session.state,''),/任务已全部勾选/);const first=f.document.querySelector('#all-tasks input');first.checked=false;await first.onchange();assert.equal(taskProgress(f.session.state.roadmap).remaining,1);assert.match(f.document.querySelector('#tasks-summary').textContent,/剩余 1 项/);await f.window.happyDOM.close();});
test('failed checkbox save displays error and restores authoritative unchecked state',async()=>{const f=fixture();f.client.updateProgress=async()=>{throw Error('保存失败');};const input=f.document.querySelector('#all-tasks input');input.checked=true;await input.onchange();assert.equal(f.document.querySelector('#all-tasks input').checked,false);assert.match(f.document.querySelector('#tasks-error').textContent,/保存失败/);assert.equal(taskProgress(f.session.state.roadmap).done,3);assert.equal(f.document.querySelector('.task-celebrate'),null);assert.equal(taskProgress(null).allDone,false);await f.window.happyDOM.close();});

test('saved task celebrates once; reduced motion keeps confirmation without particles',async()=>{const f=fixture();const input=f.document.querySelector('#all-tasks input');input.checked=true;await input.onchange();assert.ok(f.document.querySelector('.task-celebrate'));f.document.body.dataset.reduceMotion='true';const next=f.document.querySelector('[data-task-id="t1-0"]');next.checked=true;await next.onchange();assert.equal(f.document.querySelector('.task-celebrate'),null);assert.ok(f.document.querySelector('[data-task-id="t1-0"]').closest('.task').classList.contains('task-done'));await f.window.happyDOM.close();});
