import test from 'node:test';
import assert from 'node:assert/strict';
import {build} from 'esbuild';
import {fileURLToPath} from 'node:url';
import {Window} from 'happy-dom';
import {canWalk} from '../src/campus.js';
const root=fileURLToPath(new URL('../',import.meta.url));
const result=await build({entryPoints:[root+'src/world.js'],bundle:true,write:false,format:'iife',globalName:'WorldModule',plugins:[{name:'cpu-scene-harness',setup(build){build.onResolve({filter:/^\.\.\/vendor\//},args=>({path:root+'public/vendor/'+args.path.split('/').at(-1)}));build.onResolve({filter:/^three$/},()=>({path:'three-cpu',namespace:'fixture'}));build.onLoad({filter:/.*/,namespace:'fixture'},()=>({contents:`export * from ${JSON.stringify(root+'public/vendor/three.module.js')};import {Texture} from ${JSON.stringify(root+'public/vendor/three.module.js')};export class TextureLoader{load(){return new Texture();}}export class WebGLRenderer{constructor(){this.domElement=document.createElement('canvas');this.domElement.setPointerCapture=()=>{};this.shadowMap={};this.capabilities={getMaxAnisotropy:()=>8};this.info={render:{calls:0}};}setPixelRatio(){}setSize(){}render(scene,camera){window.__scene=scene;window.__camera=camera;}}`,resolveDir:root}));}}]});
function harness(position){const window=new Window();window.document.body.innerHTML='<main id="world"></main>';window.HTMLCanvasElement.prototype.getContext=()=>({fillRect(){},fillText(){}});let frame;window.requestAnimationFrame=fn=>{frame=fn;};window.eval(result.outputFiles[0].text);const visited=[],arrivals=[],notices=[];const world=window.WorldModule.createWorld({container:window.document.querySelector('#world'),position,profile:{gender:'female'},settings:{quality:'balanced'},onSpace:id=>visited.push(id),onInteract(){},onArrive:id=>arrivals.push(id),onInfo(){},isBlocked:()=>false,onNotice:message=>notices.push(message)});let now=window.performance.now();return {window,world,visited,arrivals,notices,tick(dt=16.667){now+=dt;frame(now);}};}
test('actual movement loop reaches nearby Lab at normal and low frame rates without origin detour or overshoot',async()=>{for(const dt of [16.667,50]){const f=harness({x:15,z:7});f.world.walkTo('lab');let frames=0;while(!f.arrivals.length&&frames++<300){f.tick(dt);const p=f.world.getPosition();assert.ok(p.x>14.9);assert.ok(p.z>=.99&&p.z<=7.01);assert.ok(canWalk(p.x,p.z));}assert.deepEqual(f.arrivals,['lab']);assert.ok(frames<300);assert.equal(f.notices.length,0);await f.window.happyDOM.close();}});
test('actual scene creates finite geometry, camera stays finite, and settings/reset do not teleport the student',async()=>{const f=harness({x:19.8,z:1});f.world.applySettings({quality:'high',sensitivity:1.4,reduceMotion:true});f.world.resetCamera();assert.deepEqual({...f.world.getPosition()},{x:19.8,z:1});f.world.walkTo('lab');for(let i=0;i<500&&!f.arrivals.length;i++){f.tick();assert.ok(canWalk(f.world.getPosition().x,f.world.getPosition().z));assert.ok(f.window.__camera.position.toArray().every(Number.isFinite));}assert.deepEqual(f.arrivals,['lab']);let meshes=0;f.window.__scene.traverse(o=>{if(o.isMesh){meshes++;assert.ok(o.geometry.attributes.position.array.every(Number.isFinite));}});assert.ok(meshes>50);await f.window.happyDOM.close();});
